"""baseline

Revision ID: cdf9e1c21ca7
Revises:
Create Date: 2026-07-28 19:49:15.814844

"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401  - autogenerated bodies reference it

from alembic import op  # noqa: F401

revision: str = "cdf9e1c21ca7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the change.

    Empty on purpose: this is a starting point for the chain, not a schema. The schema
    arrives with S-010 in Sprint 1. Because it creates nothing, the reversibility harness
    in `api/tests/test_reversibility.py` reports zero coverage against it and says so
    rather than reporting a green tick — see D-015.
    """


def downgrade() -> None:
    """Reverse it.

    Every migration must be genuinely reversible. With one production database and no
    staging environment, an irreversible migration is the most likely way to destroy
    the live demo, and the seed rebuild is the only other recovery path.

    Reversibility is checked by comparing the schema before and after, not by this
    function returning without raising. An empty `downgrade()` reverses an empty
    `upgrade()` perfectly and would satisfy any check built on the exit code.
    """
