"""baseline

Revision ID: cdf9e1c21ca7
Revises:
Create Date: 2026-07-28 19:49:15.814844

"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401  - autogenerated bodies reference it

from alembic import op  # noqa: F401

revision: str = "cdf9e1c21ca7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the change."""
    pass


def downgrade() -> None:
    """Reverse it.

    Every migration must be genuinely reversible. With one production database and no
    staging environment, an irreversible migration is the most likely way to destroy
    the live demo, and the seed rebuild is the only other recovery path.
    """
    pass
