"""core schema

Two relational tables and three hypertables, per `01-DESIGN.md` and S-010.

Autogenerate produced the tables; the hypertable conversions are hand-written, because
`create_hypertable` is a TimescaleDB function and no amount of model metadata implies it.

`observed_at` is in every fact table's primary key. Two reasons that agree: TimescaleDB
requires the partitioning column in any unique index, and per-pool history over a window is
the primary read. No separate index is created for that pattern — an index that is an exact
prefix of its own primary key is never-ship #20.

Revision ID: f317a85b9b46
Revises: cdf9e1c21ca7
Create Date: 2026-07-29 19:29:12.241065

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.db.models import HYPERTABLES

revision: str = "f317a85b9b46"
down_revision: str | Sequence[str] | None = "cdf9e1c21ca7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instance_catalog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("instance_type", sa.String(length=64), nullable=False),
        sa.Column("vcpu", sa.Integer(), nullable=False),
        sa.Column("memory_mb", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "provider IN ('aws', 'azure', 'gcp')", name="ck_instance_catalog_provider"
        ),
        sa.CheckConstraint("memory_mb > 0", name="ck_instance_catalog_memory_positive"),
        sa.CheckConstraint("vcpu > 0", name="ck_instance_catalog_vcpu_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "instance_type", name="uq_instance_catalog_provider_type"),
    )
    op.create_table(
        "pool",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("catalog_id", sa.Integer(), nullable=False),
        sa.Column("region", sa.String(length=32), nullable=False),
        sa.Column("zone", sa.String(length=32), nullable=False),
        sa.Column("os", sa.String(length=16), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["catalog_id"], ["instance_catalog.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("catalog_id", "region", "zone", "os", name="uq_pool_identity"),
    )
    op.create_table(
        "capacity_metric",
        sa.Column("pool_id", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capacity_score", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.CheckConstraint("source IN ('measured', 'simulated')", name="ck_capacity_metric_source"),
        sa.CheckConstraint(
            "capacity_score >= 0 AND capacity_score <= 1", name="ck_capacity_metric_range"
        ),
        sa.ForeignKeyConstraint(["pool_id"], ["pool.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pool_id", "observed_at"),
    )
    op.create_table(
        "interruption_event",
        sa.Column("pool_id", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reclaimed_count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "source IN ('measured', 'simulated')", name="ck_interruption_event_source"
        ),
        sa.CheckConstraint("reclaimed_count > 0", name="ck_interruption_event_count_positive"),
        sa.ForeignKeyConstraint(["pool_id"], ["pool.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pool_id", "observed_at"),
    )
    op.create_table(
        "price_metric",
        sa.Column("pool_id", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price_usd_hour", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.CheckConstraint("source IN ('measured', 'simulated')", name="ck_price_metric_source"),
        sa.CheckConstraint("price_usd_hour >= 0", name="ck_price_metric_non_negative"),
        sa.ForeignKeyConstraint(["pool_id"], ["pool.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pool_id", "observed_at"),
    )
    # ### end Alembic commands ###

    # The three fact tables become hypertables partitioned on observation time. The list is
    # read from the models rather than repeated here, so the migration and the schema cannot
    # disagree about which tables are partitioned.
    #
    # `if_not_exists` is deliberate: this must be safe to re-apply after a reverse that
    # failed partway, which is exactly what the reversibility harness exercises.
    for table in HYPERTABLES:
        op.execute(
            sa.text(
                "SELECT create_hypertable(:t, 'observed_at', if_not_exists => TRUE)"
            ).bindparams(t=table)
        )


def downgrade() -> None:
    """Reverse it.

    Every migration must be genuinely reversible. With one production database and no
    staging environment, an irreversible migration is the most likely way to destroy
    the live demo, and the seed rebuild is the only other recovery path.

    No explicit un-hypertable step: dropping the table drops its chunks and its TimescaleDB
    catalog entry with it. Verified rather than assumed — chunks are NOT extension-owned
    (no `pg_depend` row with `deptype = 'e'`), so the reversibility harness sees them, and a
    downgrade that orphaned one would be reported as an added relation in
    `_timescaledb_internal`.

    Children before parents: `pool` cannot be dropped while a fact table references it.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("price_metric")
    op.drop_table("interruption_event")
    op.drop_table("capacity_metric")
    op.drop_table("pool")
    op.drop_table("instance_catalog")
    # ### end Alembic commands ###
