"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401  - autogenerated bodies reference it
from alembic import op  # noqa: F401
${imports if imports else ""}

revision: str = ${repr(up_revision)}
down_revision: str | Sequence[str] | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    """Apply the change."""
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    """Reverse it.

    Every migration must be genuinely reversible. With one production database and no
    staging environment, an irreversible migration is the most likely way to destroy
    the live demo, and the seed rebuild is the only other recovery path.
    """
    ${downgrades if downgrades else "pass"}
